### ISSUE TITLE
Running the fasapi backend

### ISSUE THREAD

**Issue by Badrul-QAI** [roy-pstr/simple-auth0-fastapi-react-app#11]
Noob here - but how do I run the fastapi backend?

I tried going into the /src folder and running: uvicorn main:app --host 0.0.0.0 --port 8000

but this then told me the imports within main.py were failing:
`ModuleNotFoundError: No module named 'src'`

So then i tried going up one directory and running:
uvicorn src.main:app --host 0.0.0.0 --port 8000

but this then gave me the error:
`pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.` 

which is a different error I realise, but I want to be sure I haven't misunderstood how to run the FastAPI code (outside of the docker file).

**Comment by roy-pstr** [comment]
Thanks for your comment.

I fixed this, the code is not comparable with pydantic > 1.10. Try again to install the environment and run the backend it should work.
