### ISSUE TITLE
Poetry Group Dependency Failed

### ISSUE THREAD

**Issue by Timothy102** [roy-pstr/simple-auth0-fastapi-react-app#9]
Trying to install the packages with poetry this is the error I had received: 

"The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)"

Possible solution includes modifiying the pyproject.toml to:

`[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pylint = "^2.15.9"`

+ run poetry update to update the packeges :)

**Comment by roy-pstr** [comment]
Upgrade poetry to 1.2.0b3.
Install via: `curl -sSL https://install.python-poetry.org | python3 - --preview`
Or if you already have poetry installed: `poetry self update --preview`
